POST http://localhost:8888/.netlify/functions/word-check
Content-Type: application/json

{
  "word": "ciao"
}

###
GET http://localhost:8888/.netlify/functions/word-expired?timestamp=2022-05-29T22:18:45.536Z
Content-Type: application/json
