### Test word-check
POST http://localhost:8888/.netlify/functions/word-check
Content-Type: application/json

{
  "word": "ciao"
}

### Test word-expired
GET http://localhost:8888/.netlify/functions/word-expired
Content-Type: application/json
